### ISSUE TITLE
New Archetype Examples

### ISSUE THREAD

**Issue by johnnymatthews** [bloxbean/avm-archetype#10]
It would be helpful if developers were given new options for different types of contract. For example:

1. A simple _Getter Setter_ for new developers, similar to what is already present in the default archetype, also seen in the [docs](https://docs.aion.network/docs/apis-ethers-js-examples#section-base-contract).
2. A contract that transfers `AION`.
3. The Secret Message seen in the [Aion Docs](https://docs.aion.network/docs/fundamentals-avm-concepts-abi-types#section-contract-abi)
4. An Aion Token Standard template, as seen in the [Aion Fungible Token contract](https://github.com/jennijuju/ATS041AionFungibleTokenReferenceImplementation/blob/master/src/main/java/org/aion/AIP041TokenContract.java)
5. A Non-fungible Token template, when that is released.

**Comment by satran004** [comment]
I am exploring two options -
- Multiple archetypes
- One archetype with a new user input for contract type

I would prefer the second option as it is easy to maintain one archetype project.
