### ISSUE TITLE
Latest released version of aion4j should be default

### ISSUE THREAD

**Issue by fulldecent** [bloxbean/avm-archetype#11]
Currently shipping is 0.6.7.

I am not sure which project is initiating the releases but I recommend a file RELEASE.md be added to that repo to include a checklist. And after the release, one checklist item is to update avm-archetype to the latest released aion4j.

**Comment by satran004** [comment]
@fulldecent Thanks for pointing this out. I have updated README with the latest archetype version. 
When you use latest version (which is 0.30), the latest maven plugin version will be automatically fetched.

Good idea. I will add a RELEASE.md. I need to find a way to automatically update it during the  release process.

FYI, currently if you want to look for the latest released components. you can check  aion4j-maven-plugin-2, archtypes file under this repo.

https://github.com/bloxbean/aion4j-release

The IntelliJ plugin and avm-archetype read from this location for the latest version.

**Comment by fulldecent** [comment]
Excellent, thank you. I’m getting to point the where I’m learning and forgetting computer languages at the same speed. So if I don’t remind my future self how to maintain the projects, with specific steps, then all hope is lost. :-p
